# Generated by Django 3.2.25 on 2024-06-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='person',
            new_name='owner',
        ),
    ]
