# Generated by Django 3.2.25 on 2024-05-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdpost',
            name='image',
            field=models.ImageField(default='../default_profile_qdjgyp', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='birdpost',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='birdpost',
            name='categories',
            field=models.ManyToManyField(related_name='birdpost', to='about.Category'),
        ),
    ]
