# Generated by Django 3.2.25 on 2024-10-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdpost',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
