# Generated by Django 3.2.25 on 2024-06-19 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('birdpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birdpost',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='birdpost',
            name='categories',
        ),
        migrations.AddField(
            model_name='birdpost',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='birdpost',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_rgq6aq', upload_to='images/'),
        ),
    ]
