# Generated by Django 3.2.25 on 2024-10-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdpost', '0002_alter_birdpost_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdpost',
            name='image',
            field=models.ImageField(default='image-upload', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='birdpost',
            name='type_of_bird',
            field=models.CharField(choices=[('owl', 'OWL'), ('eagle', 'EAGLE'), ('heron', 'HERON'), ('passerine', 'PASSERINE'), ('other', 'OTHER'), ('unknown', 'UNKNOWN')], default='Choice-of-bird', max_length=60),
        ),
    ]
