# Generated by Django 3.2.25 on 2024-06-21 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('birdpost', '0002_auto_20240619_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birdpost',
            options={},
        ),
        migrations.AlterField(
            model_name='birdpost',
            name='image',
            field=models.ImageField(default='../default_profile_qdjgyp', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='birdpost',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
