# Generated by Django 3.2.25 on 2024-07-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdpost', '0005_alter_birdpost_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='birdpost',
            name='Type_of_bird',
            field=models.CharField(choices=[('owl', 'OWL'), ('eagle', 'EAGLE'), ('heron', 'HERON'), ('passerine', 'PASSERINE'), ('other', 'OTHER'), ('unknown', 'UNKNOWN')], default='unknown', max_length=60),
        ),
    ]
